### PR TITLE
Wkhtml27

### PR DESCRIPTION
**Pull request by sensei-hacker**
This has been updated to work with Moodle 2.7/2.8 and I've done various fixes and improvements.  After trying out two or three different html2pdf renderers, I decided on wkhtml.  I'll be doing more work on it over the next month or two as we formally test it with the academic department which will be using it, then roll it out to production.

### CODE REVIEW

**Comment by cpavlina** [comment]
There was a branch last year that started to implement something similar to this, but wasn't completed. Have you seen the WIP_BU_78_WEBKIT branch?

https://github.com/bumoodle/moodle-quiz_papercopy/tree/WIP_BU_78_WEBKIT

**Comment by MorrisR2** [comment]
My code includes quite a bit from WIP_BU_78_WEBKIT.  It also works correctly on Moodle 2.7/2.8 and fixes a few bugs existing in WIP_BU_78_WEBKIT.

**Comment by sensei-hacker** [comment]
@cpavlina  so I guess you've taken over for @ktemkin ?  I tried to contact Kyle for about a year to coordinate efforts before undertaking this work, but didn't get much response. I've been working on quiz_papercopy and its companion theme_pdf. We are scheduled to start integration testing on Friday, so I expect we'll a few more commits over the next month or two. Eventually we'll be putting many thousands of students through the system.

**Comment by alexisvl** [comment]
Yup, for a while at least. Kyle's not at the university anymore.

**Comment by sensei-hacker** [comment]
Good to meet you.  The one message I got from Kyle was that he had planned to do significant updates last summer. Do you have anything planned, so we can coordinate, or will my branches be the development branches for the next year or so?

**Pull request merged**
